### PR TITLE
Update all packages and frameworks

### PR DESCRIPTION
**Pull request by Foxite**
I tried to use codeessentials.Extensions.Logging.Demystifier but I got a TypeLoadException which seemed to be caused by the fact that this package is built against an old version of Ben.Demystifier. I have updated all PackageReferences in this repository to the latest versions. I have verified through the unit tests, and by referencing the updated project from my app, that the netstandard2.0 version of the package works properly now.

I was not able to verify that the net461 version works properly because I don't have it installed and it's difficult to do so on my linux machine. However, I don't see why it wouldn't work.

I've also updated the target frameworks of the sample projects to make sure they still compile (I don't have netcoreapp2.0 installed).

### CODE REVIEW

**Comment by Foxite** [comment]
CI tests have failed because they're not set up to use net core 3.1.

**Comment by twenzel** [comment]
@Foxite Please update `appveyor.yml` also by updating the image to `Visual Studio 2022`.

**Comment by Foxite** [comment]
Now it's complaining about using a package which I guess is deprecated, I think the correct fix is to switch to a different ASP.NET package. I can do this tomorrow.

**Comment by Foxite** [comment]
I've updated the samples to net6.0 and verified that they work, in the console that is, because the ASP.NET developer exception page doesn't show the demystified exception and I wasn't able to get it to do so. Is that supposed to be the case?

**Pull request merged**
